// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateTask implements createTask operation.
//
// Submit a task.
//
// POST /v1/tasks
func (UnimplementedHandler) CreateTask(ctx context.Context, req *CreateTaskRequest) (r CreateTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTask implements getTask operation.
//
// GET /v1/tasks/{id}
func (UnimplementedHandler) GetTask(ctx context.Context, params GetTaskParams) (r GetTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}
