// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package queries

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const appendOutboxBatch = `-- name: AppendOutboxBatch :batchexec
INSERT INTO outbox_events (event_id, aggregate_id, type, envelope_ver, trace_id, payload)
VALUES ($1, $2, $3, $4, $5, $6)
`

type AppendOutboxBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type AppendOutboxBatchParams struct {
	EventID     uuid.UUID `json:"event_id"`
	AggregateID uuid.UUID `json:"aggregate_id"`
	Type        string    `json:"type"`
	EnvelopeVer int16     `json:"envelope_ver"`
	TraceID     *string   `json:"trace_id"`
	Payload     []byte    `json:"payload"`
}

// One round trip for N events. This sits inside the same transaction as the
// state change, so its latency is lock-hold time on the hot tasks row.
// sent/created_at take their column defaults; envelope_ver comes from
// domain.EnvelopeVersion on the Go side (the column is the one source).
func (q *Queries) AppendOutboxBatch(ctx context.Context, arg []AppendOutboxBatchParams) *AppendOutboxBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.EventID,
			a.AggregateID,
			a.Type,
			a.EnvelopeVer,
			a.TraceID,
			a.Payload,
		}
		batch.Queue(appendOutboxBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &AppendOutboxBatchBatchResults{br, len(arg), false}
}

func (b *AppendOutboxBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *AppendOutboxBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
