// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/google/uuid"
)

type Task struct {
	ID             uuid.UUID `json:"id"`
	IdempotencyKey *string   `json:"idempotency_key"`
	Payload        []byte    `json:"payload"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
}
