// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID             pgtype.UUID        `json:"id"`
	IdempotencyKey *string            `json:"idempotency_key"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
