// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error)
	GetTaskByIdempotencyKey(ctx context.Context, idempotencyKey *string) (Task, error)
}

var _ Querier = (*Queries)(nil)
