// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, idempotency_key, payload, handler)
VALUES ($1, $2, $3, $4)
RETURNING id, idempotency_key, payload, status, created_at, handler
`

type CreateTaskParams struct {
	ID             uuid.UUID `json:"id"`
	IdempotencyKey *string   `json:"idempotency_key"`
	Payload        []byte    `json:"payload"`
	Handler        string    `json:"handler"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.IdempotencyKey,
		arg.Payload,
		arg.Handler,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.Handler,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, idempotency_key, payload, status, created_at, handler
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.Handler,
	)
	return i, err
}

const getTaskByIdempotencyKey = `-- name: GetTaskByIdempotencyKey :one
SELECT id, idempotency_key, payload, status, created_at, handler
FROM tasks
WHERE idempotency_key = $1
`

func (q *Queries) GetTaskByIdempotencyKey(ctx context.Context, idempotencyKey *string) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByIdempotencyKey, idempotencyKey)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.Handler,
	)
	return i, err
}
