// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO task_attempts (
    id, task_id, attempt, worker_id, status,
    started_at, finished_at, last_heartbeat, error_class, error_message
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
)
RETURNING id, task_id, attempt, worker_id, status, started_at, finished_at, last_heartbeat, progress_pct, error_class, error_message, error_stack
`

type CreateAttemptParams struct {
	ID            uuid.UUID  `json:"id"`
	TaskID        uuid.UUID  `json:"task_id"`
	Attempt       int32      `json:"attempt"`
	WorkerID      string     `json:"worker_id"`
	Status        string     `json:"status"`
	StartedAt     time.Time  `json:"started_at"`
	FinishedAt    *time.Time `json:"finished_at"`
	LastHeartbeat *time.Time `json:"last_heartbeat"`
	ErrorClass    *string    `json:"error_class"`
	ErrorMessage  *string    `json:"error_message"`
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (TaskAttempt, error) {
	row := q.db.QueryRow(ctx, createAttempt,
		arg.ID,
		arg.TaskID,
		arg.Attempt,
		arg.WorkerID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.LastHeartbeat,
		arg.ErrorClass,
		arg.ErrorMessage,
	)
	var i TaskAttempt
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Attempt,
		&i.WorkerID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastHeartbeat,
		&i.ProgressPct,
		&i.ErrorClass,
		&i.ErrorMessage,
		&i.ErrorStack,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    id, idempotency_key, payload, handler,
    tenant_id, priority, earliest_at, attempt, max_attempts,
    shard_id, cancel_requested, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11, $12
)
RETURNING id, idempotency_key, payload, status, created_at, handler, tenant_id, priority, earliest_at, attempt, max_attempts, shard_id, cancel_requested, updated_at, started_at, worker_id, lease_until, lease_epoch, trace_id
`

type CreateTaskParams struct {
	ID              uuid.UUID `json:"id"`
	IdempotencyKey  *string   `json:"idempotency_key"`
	Payload         []byte    `json:"payload"`
	Handler         string    `json:"handler"`
	TenantID        uuid.UUID `json:"tenant_id"`
	Priority        int16     `json:"priority"`
	EarliestAt      time.Time `json:"earliest_at"`
	Attempt         int32     `json:"attempt"`
	MaxAttempts     int32     `json:"max_attempts"`
	ShardID         int32     `json:"shard_id"`
	CancelRequested bool      `json:"cancel_requested"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.IdempotencyKey,
		arg.Payload,
		arg.Handler,
		arg.TenantID,
		arg.Priority,
		arg.EarliestAt,
		arg.Attempt,
		arg.MaxAttempts,
		arg.ShardID,
		arg.CancelRequested,
		arg.UpdatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.Handler,
		&i.TenantID,
		&i.Priority,
		&i.EarliestAt,
		&i.Attempt,
		&i.MaxAttempts,
		&i.ShardID,
		&i.CancelRequested,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.WorkerID,
		&i.LeaseUntil,
		&i.LeaseEpoch,
		&i.TraceID,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, idempotency_key, payload, status, created_at, handler, tenant_id, priority, earliest_at, attempt, max_attempts, shard_id, cancel_requested, updated_at, started_at, worker_id, lease_until, lease_epoch, trace_id FROM tasks WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.Handler,
		&i.TenantID,
		&i.Priority,
		&i.EarliestAt,
		&i.Attempt,
		&i.MaxAttempts,
		&i.ShardID,
		&i.CancelRequested,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.WorkerID,
		&i.LeaseUntil,
		&i.LeaseEpoch,
		&i.TraceID,
	)
	return i, err
}

const getTaskByIdempotencyKey = `-- name: GetTaskByIdempotencyKey :one
SELECT id, idempotency_key, payload, status, created_at, handler, tenant_id, priority, earliest_at, attempt, max_attempts, shard_id, cancel_requested, updated_at, started_at, worker_id, lease_until, lease_epoch, trace_id FROM tasks WHERE idempotency_key = $1
`

func (q *Queries) GetTaskByIdempotencyKey(ctx context.Context, idempotencyKey *string) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByIdempotencyKey, idempotencyKey)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.Handler,
		&i.TenantID,
		&i.Priority,
		&i.EarliestAt,
		&i.Attempt,
		&i.MaxAttempts,
		&i.ShardID,
		&i.CancelRequested,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.WorkerID,
		&i.LeaseUntil,
		&i.LeaseEpoch,
		&i.TraceID,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO idempotency_keys (tenant_id, handler, idempotency_key, task_id, payload_hash)
VALUES ($1, $2, $3, $4, $5)
`

type InsertIdempotencyKeyParams struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	Handler        string    `json:"handler"`
	IdempotencyKey string    `json:"idempotency_key"`
	TaskID         uuid.UUID `json:"task_id"`
	PayloadHash    []byte    `json:"payload_hash"`
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyKey,
		arg.TenantID,
		arg.Handler,
		arg.IdempotencyKey,
		arg.TaskID,
		arg.PayloadHash,
	)
	return err
}

const listTaskAttempts = `-- name: ListTaskAttempts :many
SELECT id, task_id, attempt, worker_id, status, started_at, finished_at, last_heartbeat, progress_pct, error_class, error_message, error_stack FROM task_attempts WHERE task_id = $1 ORDER BY attempt
`

// Ordered by attempt so the aggregate rebuilds its history in the order it
// happened; Task.finishOpenAttempt only ever looks at the last element.
func (q *Queries) ListTaskAttempts(ctx context.Context, taskID uuid.UUID) ([]TaskAttempt, error) {
	rows, err := q.db.Query(ctx, listTaskAttempts, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskAttempt
	for rows.Next() {
		var i TaskAttempt
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Attempt,
			&i.WorkerID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.LastHeartbeat,
			&i.ProgressPct,
			&i.ErrorClass,
			&i.ErrorMessage,
			&i.ErrorStack,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
